[project]
name = "vmess-aead"
version = "0.1.0"
description = "VMessAEAD packet parser for python."
authors = [{ name = "Mix", email = "32300164+mnixry@users.noreply.github.com" }]
dependencies = [
    "cryptography>=42.0.0", #  42.0.0 is the first version that supports SM4-GCM
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
cli = [
    "rich>=13.7.0", #Rich is used to support colored logging
    "typer>=0.9.0", #Typer is used to support command line interface
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.2.1",
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
    "pytest-pretty>=1.2.0",
]

[tool.pdm.scripts]
test = { cmd = ["pytest", "--cov", "./src/", "--cov-report=term-missing", "."] }
lint = "ruff --fix"

[tool.ruff]
lint.select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]
target-version = "py310"
